import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const root = new URL('../', import.meta.url);

test('content editor workbench provides structured page and product edits through the current Directus session', async () => {
  const [manifestText, index, module] = await Promise.all([
    readFile(new URL('extensions/content-editor-workbench/package.json', root), 'utf8'),
    readFile(new URL('extensions/content-editor-workbench/src/index.js', root), 'utf8'),
    readFile(new URL('extensions/content-editor-workbench/src/module.vue', root), 'utf8')
  ]);
  const manifest = JSON.parse(manifestText);

  assert.equal(manifest['directus:extension'].type, 'module');
  assert.equal(manifest['directus:extension'].source, 'src/index.js');
  assert.match(index, /ruijun-content-editor-workbench/);
  assert.match(module, /页面段落/);
  assert.match(module, /产品系列/);
  assert.match(module, /受控系列封面/);
  assert.match(module, /企业资料/);
  assert.match(module, /发展历程/);
  assert.match(module, /资质证书/);
  assert.match(module, /制造证据/);
  assert.match(module, /服务支持/);
  assert.match(module, /文章与案例/);
  assert.match(module, /媒体资产/);
  assert.match(module, /登记待审核媒体/);
  assert.match(module, /上传并登记候选素材/);
  assert.match(module, /常见问题知识/);
  assert.match(module, /常见问题知识草稿编辑/);
  assert.match(module, /受控知识媒体/);
  assert.match(module, /保存常见问题知识草稿/);
  assert.match(module, /审核队列/);
  assert.match(module, /待审核内容/);
  assert.match(module, /批准进入待发布/);
  assert.match(module, /退回修改/);
  assert.match(module, /提交审核/);
  assert.match(module, /可提交草稿/);
  assert.match(module, /恢复草稿/);
  assert.match(module, /恢复为草稿/);
  assert.match(module, /新闻与文章/);
  assert.match(module, /客户案例/);
  assert.match(module, /新建草稿/);
  assert.match(module, /全站设置/);
  assert.match(module, /受控品牌标志素材/);
  assert.match(module, /全站导航与联系方式/);
  assert.match(module, /当前业务审核标记/);
  assert.match(module, /服务资料/);
  assert.match(module, /服务网点/);
  assert.match(module, /售后入口/);
  assert.match(module, /独立技术参数/);
  assert.match(module, /normalizeSections/);
  assert.match(module, /normalizeSettings/);
  assert.match(module, /normalizeArticle/);
  assert.match(module, /createEditorialRecord/);
  assert.match(module, /saveEditorialRecord/);
  assert.match(module, /reviewedMediaAssets/);
  assert.match(module, /isReviewedMediaAsset/);
  assert.match(module, /normalizeMediaReferences/);
  assert.match(module, /addCompanyMediaReference/);
  assert.match(module, /removeCompanyMediaReference/);
  assert.match(module, /addModelMediaReference/);
  assert.match(module, /removeModelMediaReference/);
  assert.match(module, /受控型号媒体/);
  assert.match(module, /assets: companyDraft\.value\.mediaReferences/);
  assert.match(module, /media: companyDraft\.value\.mediaReferences/);
  assert.match(module, /media: modelDraft\.value\.mediaReferences/);
  assert.match(module, /选择已发布资质素材/);
  assert.match(module, /选择已发布制造素材/);
  assert.match(module, /loadMediaAssets/);
  assert.match(module, /loadMediaCandidates/);
  assert.match(module, /loadMediaPreviews/);
  assert.match(module, /loadMediaPreview/);
  assert.match(module, /responseType: 'blob'/);
  assert.match(module, /URL\.createObjectURL/);
  assert.match(module, /URL\.revokeObjectURL/);
  assert.match(module, /media-preview/);
  assert.match(module, /loadKnowledge/);
  assert.match(module, /normalizeKnowledge/);
  assert.match(module, /saveKnowledge/);
  assert.match(module, /addKnowledgeMediaReference/);
  assert.match(module, /removeKnowledgeMediaReference/);
  assert.match(module, /media: knowledgeDraft\.value\.mediaReferences/);
  assert.match(module, /filteredKnowledge/);
  assert.match(module, /contentQueueDefinitions/);
  assert.match(module, /loadReviewQueue/);
  assert.match(module, /loadSubmissionQueue/);
  assert.match(module, /review_note/);
  assert.match(module, /review-note-display/);
  assert.match(module, /Promise\.allSettled/);
  assert.match(module, /submitForReview/);
  assert.match(module, /restoreDraft/);
  assert.match(module, /filter\[status\]\[_in\]/);
  assert.match(module, /decideReview/);
  assert.match(module, /status: 'review', review_note/);
  assert.match(module, /status, review_note/);
  assert.match(module, /createMediaCandidate/);
  assert.match(module, /validateMediaFile/);
  assert.match(module, /api\.post\('\/files', form\)/);
  assert.match(module, /api\.post\('\/items\/media_assets'/);
  assert.match(module, /api\.patch\(`\/items\/knowledge_items/);
  assert.match(module, /status: 'draft'/);
  assert.match(module, /publication_state: 'unpublished'/);
  assert.match(module, /validateSettingLinks/);
  assert.match(module, /reviewedMediaAssets\('brand'\)/);
  assert.match(module, /requires_business_review/);
  assert.match(module, /validateSections/);
  assert.match(module, /requires_claim_review/);
  assert.match(module, /editableStatuses/);
  assert.match(module, /api\.patch\(`\/items\/pages/);
  assert.match(module, /api\.patch\(`\/items\/product_series/);
  assert.match(module, /cover_asset: seriesDraft\.value\.cover_asset/);
  assert.match(module, /api\.patch\(`\/items\/product_models/);
  assert.match(module, /api\.patch\(`\/items\/product_parameters/);
  assert.match(module, /api\.patch\(`\/items\/\$\{encodeURIComponent\(companyMode\.value\)\}/);
  assert.match(module, /api\.patch\(`\/items\/\$\{encodeURIComponent\(serviceMode\.value\)\}/);
  assert.match(module, /api\.patch\(`\/items\/site_settings/);
  assert.match(module, /api\.patch\(`\/items\/\$\{encodeURIComponent\(editorialMode\.value\)\}/);
  assert.match(module, /api\.post\(`\/items\/\$\{encodeURIComponent\(editorialMode\.value\)\}/);
  assert.match(module, /filter\[status\]\[_eq\]/);
  assert.match(module, /filter\[publication_state\]\[_eq\]/);
  assert.doesNotMatch(module, /date_created/);
  assert.match(module, /api\.post\('\/items\/product_parameters'/);
  assert.match(module, /内容版本审计/);
  assert.match(module, /三步完成一次更新/);
  assert.match(module, /从这里开始/);
  assert.match(module, /今天想更新什么？/);
  assert.match(module, /修改官网页面/);
  assert.match(module, /更新产品资料/);
  assert.match(module, /维护服务支持/);
  assert.match(module, /更多工具/);
  assert.match(module, /const activeTab = ref\('home'\)/);
  assert.match(module, /editor-start/);
  assert.match(module, /预览当前草稿/);
  assert.match(module, /更多工具/);
  assert.match(module, /常用内容/);
  assert.match(module, /编辑/);
  assert.match(module, /送审/);
  assert.match(module, /高级设置（一般无需修改）/);
  assert.match(module, /helpOpen/);
  assert.match(module, /selectTab/);
  assert.match(module, /previewOpen/);
  assert.match(module, /previewKind/);
  assert.match(module, /websitePreviewTarget/);
  assert.match(module, /content-preview-tokens\/issue/);
  assert.match(module, /preview_open_url/);
  assert.match(module, /草稿预览/);
  assert.match(module, /有未保存修改/);
  assert.match(module, /currentDraftFingerprint/);
  assert.match(module, /confirmDiscardChanges/);
  assert.match(module, /当前内容有未保存的修改/);
  assert.match(module, /requestReload/);
  assert.match(module, /beforeunload/);
  assert.match(module, /handleBeforeUnload/);
  assert.match(module, /page-preview/);
  assert.match(module, /article-preview/);
  assert.match(module, /product-preview/);
  assert.match(module, /提交审核/);
  assert.match(module, /恢复草稿/);
  assert.match(module, /知识库同步状态（系统维护）/);
  assert.match(module, /knowledgeSyncStatusLabel/);
  assert.match(module, /暂不满足同步条件/);
  assert.doesNotMatch(module, /<small>\/\{\{ page\.slug \}\}<\/small>/);
  assert.doesNotMatch(module, /SUBMIT FOR REVIEW|RESTORE DRAFT/);
  assert.doesNotMatch(module, />STRUCTURED CONTENT EDITOR</);
  assert.doesNotMatch(module, />PRODUCT SERIES</);
  assert.doesNotMatch(module, /CMS_BFF_TOKEN|CMS_WRITE_TOKEN|ADMIN_PASSWORD/);
  assert.match(module, /repair_page_configs/);
  assert.match(module, /repair_home/);
  assert.match(module, /action_cards/);
  assert.match(module, /saveRepairPage/);
  assert.match(module, /loadRepairPages/);
  assert.match(module, /repair-page-preview/);
});
