import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
import test from 'node:test';

test('product catalog keeps six desktop families in one viewport with single-line labels', async () => {
  const page = await readFile(new URL('../pages/product/[slug].vue', import.meta.url), 'utf8');

  assert.match(page, /height: 395px/);
  assert.match(page, /title: 'Our product', kicker: '我们的产品'/);
  assert.match(page, /const categoriesCopy = computed\(\(\) => productSection\('categories', \{ kicker: '3大', title: '选择瑞钧理由' \}\)\);/);
  assert.match(page, /title: 'Champion', body: '销量持续领先，品质始终如一'/);
  assert.match(page, /const section = productSection\(id, fallback\);\s*return \{\s*id,\s*\.\.\.fallback,\s*\.\.\.section/);
  assert.match(page, /const productPageRecord = computed\(\(\) => overlayRecord\('pages', productPageResponse\.value\?\.data \|\| null\)\);/);
  assert.match(page, /const productPageSections = computed\(\(\) => Array\.isArray\(productPageRecord\.value\?\.sections\)/);
  assert.match(page, /const productPageContent = computed\(\(\) => \(\{[\s\S]*productPageRecord\.value[\s\S]*sections: productPageSections\.value/);
  assert.match(page, /data-cms-preview-key="categories"/);
  assert.match(page, /:data-cms-preview-key="proof\.id"/);
  assert.match(page, /v-bind="sectionPresentationAttributes\(proof\)"/);
  assert.doesNotMatch(page, /NO\.0|NO\.\$\{value\}/);
  assert.match(page, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(page, /\.product-grid \{[^}]*max-width: 1280px/s);
  assert.match(page, /aspect-ratio: 420 \/ 259/);
  assert.match(page, /\.product-card \{[^}]*display: block;[^}]*width: 100%/s);
  assert.match(page, /\.product-copy \{[^}]*width:36%/s);
  assert.match(page, /\.product-kicker \{[^}]*white-space:nowrap/s);
  assert.match(page, /\.product-name \{[^}]*white-space:nowrap/s);
  assert.match(page, /'is-selected': detailsOpen && selectedCard === family\.id/);
  assert.match(page, /class="details-jump"/);
  assert.match(page, /const catalogPageSize = computed/);
  assert.match(page, /paginationCopy\.value\?\.pagination\?\.page_size/);
  assert.match(page, /Math\.min\(Math\.max\(value, 1\), 6\) : 6/);
  assert.match(page, /const visibleCatalogCards = computed/);
  assert.match(page, /function fallbackProductCardForSeries\(series: any, index: number\)/);
  assert.match(page, /'ft-xs': 'ft'/);
  assert.match(page, /'fl-xs': 'fl'/);
  assert.match(page, /fallbackProductCardForSeries\(series, index\)\?\.image/);
  assert.match(page, /id: 'fl'[^\n]+product-fl-xs\.png/);
  assert.match(page, /v-for="\(family, pageIndex\) in visibleCatalogCards"/);
  assert.match(page, /function seriesCardItemId\(index: number, _fallback: string\)/);
  assert.match(page, /class="product-card-wrap"[^>]*data-cms-preview-collection="product_series"[^>]*:data-cms-preview-item-id="seriesCardItemId\(/);
  assert.match(page, /:data-cms-preview-key="seriesCardItemId/);
  assert.match(page, /\? seriesCardValue\(/);
  assert.match(page, /<button[^>]*class="product-card"[^>]*data-cms-preview-field-path="name"[^>]*@click="openProduct\(family\.id\)"/);
  assert.match(page, /data-cms-preview-field-path="cover_asset"/);
  assert.match(page, /data-cms-preview-field-path="positioning"/);
  assert.match(page, /data-cms-preview-field-path="name"/);
  assert.doesNotMatch(page, /:data-cms-preview-field-path="`items\.\$\{pageIndex\}\.(cover_asset|positioning|name)`"/);
  assert.match(page, /id="product-details"[^>]*:data-cms-preview-collection="productBinding\('title'\)\.collection"/);
  assert.match(page, /:data-cms-preview-item-id="productBinding\('title'\)\.itemId"/);
  assert.match(page, /class="series-model-list"[^>]*aria-label="该系列机型"/);
  assert.match(page, /<span v-bind="fieldPresentationAttributes\(selectedModelRecord\?\.presentation, 'model_code'\)" data-cms-preview-field-path="model_code" data-cms-preview-position-field-path="presentation\.field_presentation\.model_code">\{\{ model \}\}<\/span>/);
  assert.match(page, /fieldPresentationAttributes\(displayConfig, featurePresentationPath\(index, 'label'\)\)[\s\S]*data-cms-preview-field-path="`configuration\.features\.\$\{index\}\.label`"[\s\S]*data-cms-preview-position-field-path="`configuration\.field_presentation\.\$\{featurePresentationPath\(index, 'label'\)\}`"/);
  assert.match(page, /data-cms-preview-field-path="`configuration\.features\.\$\{index\}\.image`"[\s\S]*data-cms-preview-position-field-path="`configuration\.field_presentation\.\$\{featurePresentationPath\(index, 'image'\)\}`"/);
  assert.match(page, /const activeSeriesCode = computed\(\(\) => \{[\s\S]*previewModelSeries[\s\S]*return previewModelSeries/);
  assert.match(page, /previewSession\.value\?\.collection === 'product_models' \|\| !slug\.value/);
  assert.match(page, /product\.value\?\.series_code \|\| previewSession\.value\.preview\?\.series_code/);
  assert.match(page, /const activePreviewModel = previewSession\.value\?\.collection === 'product_models' \? product\.value\?\.model_code : '';/);
  assert.match(page, /const activeSeriesDetail = computed\(\(\) => psdSeriesDetails\[psdDetailKey\(\{ \.\.\.activeCard\.value, id: activeSeriesCode\.value \|\| activeCard\.value\?\.id \}\)\]/);
  assert.match(page, /const previewModel = product\.value && String\(product\.value\.series_code \|\| ''\) === activeSeriesCode\.value \? product\.value : null;/);
  assert.match(page, /import \{ groupPreviewProductParameters, normalizePreviewParameterGroups \} from '~\/shared\/product-preview-parameters\.mjs';/);
  assert.match(page, /const normalized = normalizePreviewParameterGroups\(groups\);/);
  assert.match(page, /:data-cms-preview-item-id="item\.id \|\| undefined"/);
  assert.match(page, /:data-cms-preview-field-path="item\.id \? 'unit' : undefined"/);
  assert.match(page, /if \(!slug\.value \|\| !publicModels\.value\.length\) return previewModel \? \[previewModel, \.\.\.psdModels\.filter/);
  assert.match(page, /<b[^>]*data-cms-preview-field-path="kicker"[^>]*>\{\{ categoriesCopy\.kicker \|\| '3大' \}\}<\/b>/);
  assert.match(page, /<span[^>]*class="cms-styled-text"[^>]*data-cms-preview-field-path="title"[^>]*>\{\{ categoriesCopy\.title \}\}<\/span>/);
  assert.match(page, /:data-cms-preview-field-path="proof\.value \? 'value' : 'title'"/);
  assert.match(page, /:data-cms-preview-field-path="proof\.value \? 'unit' : 'body'"/);
  assert.match(page, /watch\(\[proofCopy, previewSession\], \(\[proofs, session\]\) => \{[\s\S]*if \(!session \|\| !proofDomReady\.value\) return;[\s\S]*syncPreviewProofNumbers\(proofs\)/);
  assert.match(page, /const proofDomReady = ref\(false\);/);
  assert.match(page, /if \(!session \|\| !proofDomReady\.value\) return;/);
  assert.match(page, /onMounted\(\(\) => \{[\s\S]*proofDomReady\.value = true;[\s\S]*if \(previewSession\.value\) syncPreviewProofNumbers\(\);/);
  assert.match(page, /const animateProof = \(now: number\) => \{[\s\S]*if \(previewSession\.value\) \{\s*syncPreviewProofNumbers\(\);\s*return;[\s\S]*if \(previewSession\.value\) syncPreviewProofNumbers\(\);/);
  assert.match(page, /data-cms-preview-field-path="configuration\.intro\.title"/);
  assert.match(page, /:data-cms-preview-field-path="displayImageFieldPath"/);
  assert.match(page, /<img :src="String\(displayConfig\.labels\?\.technicalImage \|\| '\/assets\/psd\/technical-label-psd\.png'\)" :alt="String\(displayLabels\.technical \|\| parametersCopy\.title \|\| '技术参数'\)" :data-cms-preview-field-path="'configuration\.labels\.technical_image_asset_id'"[^>]*data-cms-preview-media-role="technical">/);
  assert.match(page, /:data-cms-preview-field-path="`configuration\.drawings\.\$\{activeDrawing\.sourceIndex\}\.caption`"/);
  assert.match(page, /:data-cms-preview-field-path="`configuration\.drawings\.\$\{activeDrawing\.sourceIndex\}\.media_asset_id`"/);
  assert.match(page, /:data-cms-preview-placement-key="'product\.gallery\.image'"/);
  assert.doesNotMatch(page, /<img v-else src="\/assets\/psd\/product-dimensions\.png"[^>]*data-cms-preview-field-path/);
  assert.match(page, /class="catalog-pager"/);
  assert.match(page, /const paginationCopy = computed\(\(\) => productSection\('pagination', \{[\s\S]*pagination: \{ page_size: 6, previous_label: '上一页', next_label: '下一页' \}/);
  assert.match(page, /data-cms-preview-field-path="pagination\.previous_label"/);
  assert.match(page, /data-cms-preview-field-path="pagination\.next_label"/);
  assert.match(page, /@click="changeCatalogPage\(-1\)"/);
  assert.match(page, /@click="changeCatalogPage\(1\)"/);
  assert.match(page, /scrollIntoView\(\{ behavior: 'smooth', block: 'start' \}\)/);
  assert.match(page, /\.product-grid\.has-selection \.product-card\.is-selected \{[^}]*translateY\(-18px\)/s);
  assert.match(page, /\.series-specification \{[^}]*clamp\(260px, 15\.625vw, 300px\)/s);
  assert.match(page, /\.specification-drawings \{[^}]*align-self:end/s);
  assert.match(page, /@media \(min-width: 901px\) \{[\s\S]*\.series-specification \{[^}]*min-height: 650px/s);
  assert.match(page, /\.specification-table dl \{[^}]*min-height: 520px;[^}]*grid-auto-rows: minmax\(32px, auto\)/s);
  assert.match(page, /\.specification-table dt,[\s\S]*\.specification-table dd \{[^}]*font-size: clamp\(14px, \.85vw, 16px\)/s);
  assert.match(page, /\.specification-drawings img \{[^}]*height: 100%;[^}]*max-height: 650px[^}]*object-fit: contain/s);
  assert.match(page, /@media \(max-width: 900px\) \{[\s\S]*\.specification-table dl \{[^}]*height: auto;[^}]*grid-auto-rows: auto/s);
  assert.match(page, /class="series-capability"/);
  assert.match(page, /models: \['FR400XS\(auto\)', 'FR500XS\(auto\)', 'FR600XS\(auto\)', 'FR7055XS\(auto\)', 'FR8055XS\(auto\)', 'FR8060XS\(auto\)'\]/);
  assert.match(page, /models: \['FR-Y8060', 'FR-Y1080'\]/);
  assert.match(page, /models: \['FL8060XS\(pro\)', 'FL1180XS\(pro\)', 'FL1390XS\(pro\)', 'FL1610XS\(pro\)', 'FL2160XS\(pro\)'\]/);
  assert.match(page, /灵动切割工作站搭载自动穿丝系统/);
  assert.match(page, /表中所述加工性能参数是在本公司指定条件/);
  assert.doesNotMatch(page, /\.series-capabilities button\.active img|\.series-capabilities button:hover img/);
  assert.match(page, /--product-content-edge: max\(6\.2%, calc\(\(100% - 1400px\) \/ 2\)\)/);
  assert.match(page, /--product-arc-width: min\(22\.526vw, 432\.5px\)/);
  assert.match(page, /\.product-overview::after \{[^}]*right: calc\(var\(--product-content-edge\) - var\(--product-arc-outset\)\)/s);
  assert.match(page, /product-overview-arc\.png/);
  await access(new URL('../public/assets/psd/product-overview-arc.png', import.meta.url));
  await access(new URL('../public/assets/psd/product-detail/workstation-machine.png', import.meta.url));
  await access(new URL('../public/assets/psd/product-detail/auto-threading.png', import.meta.url));
  await access(new URL('../public/assets/psd/product-detail/fl-machine.png', import.meta.url));
  assert.match(page, /<div class="overview-kicker cms-positioned"[^>]*data-cms-preview-key="categories"[^>]*aria-hidden="true"><b[^>]*data-cms-preview-field-path="kicker"[^>]*>\{\{ categoriesCopy\.kicker \|\| '3大' \}\}<\/b>/);
  assert.match(page, /--product-kicker-outset: min\(3\.4375vw, 66px\)/);
  assert.match(page, /\.overview-kicker \{[^}]*right: calc\(var\(--product-content-edge\) - var\(--product-kicker-outset\)\)/s);
  assert.match(page, /\.overview-kicker span \{[^}]*font-size: min\(1\.875vw, 36px\)/s);
  assert.match(page, /\.overview-kicker \{[^}]*z-index: 1/);
  assert.match(page, /\.overview-heading \{[^}]*top: min\(6\.875vw, 132px\)[^}]*left: max\(6\.2%, calc\(\(100% - 1280px\) \/ 2\)\)/s);
  assert.match(page, /--product-grid-width: min\(1280px, calc\(100% - \(2 \* var\(--product-content-edge\)\)\)\)/);
  assert.match(page, /\.proof-grid \{[^}]*top: min\(13\.646vw, 261px\)[^}]*width: var\(--product-grid-width\)/s);
  assert.match(page, /\.product-overview::after \{[^}]*top: calc\(min\(3\.36vw, 64\.5px\) - 72px\)/s);
  assert.doesNotMatch(page, /\.product-overview::after \{[^}]*border-radius|\.product-overview::after \{[^}]*rotate\(/s);
});

test('visible resource and case section kickers retain their exact CMS field bindings', async () => {
  const page = await readFile(new URL('../pages/product/[slug].vue', import.meta.url), 'utf8');

  assert.match(page, /data-cms-preview-key="resources"[^>]*:data-cms-preview-collection="productBinding\('resources'\)\.collection"[^>]*:data-cms-preview-item-id="productBinding\('resources'\)\.itemId"/);
  assert.match(page, /data-cms-preview-key="resources"[\s\S]{0,420}<p class="eyebrow">\{\{ resourcesCopy\.kicker \}\}<\/p>/);
  assert.doesNotMatch(page, /data-cms-preview-key="resources"[\s\S]{0,420}<p class="eyebrow" data-cms-preview-field-path="kicker"/);
  assert.match(page, /v-for="\(resource, resourceIndex\) in resources"/);
  assert.match(page, /:data-cms-preview-field-path="`resources\.\$\{resourceIndex\}\.title`"/);
  assert.match(page, /:data-cms-preview-link-field-path="`resources\.\$\{resourceIndex\}\.url`"/);
  assert.match(page, /<span[^>]*:data-cms-preview-field-path="`resources\.\$\{resourceIndex\}\.type`">/);
  assert.match(page, /<strong[^>]*:data-cms-preview-field-path="`resources\.\$\{resourceIndex\}\.title`">/);
  assert.match(page, /data-cms-preview-key="cases"[\s\S]{0,420}<p class="eyebrow" data-cms-preview-field-path="kicker">/);
});

test('product catalog fallback images follow the CMS series identity', async () => {
  const page = await readFile(new URL('../pages/product/[slug].vue', import.meta.url), 'utf8');

  assert.match(page, /function fallbackProductCardForSeries\(series: any, index: number\)/);
  assert.match(page, /'fr-pro': 'pro'/);
  assert.match(page, /'ft-xs': 'ft'/);
  assert.match(page, /'fl-xs': 'fl'/);
  assert.match(page, /fallbackProductCardForSeries\(series, index\)\?\.image/);
  assert.match(page, /id: 'fl'[^\n]+product-fl-xs\.png/);
});
